### ISSUE TITLE
Unable to start using clustermode

### ISSUE THREAD

**Issue by raghu999** [us3r/apache-nifi#2]
Hello Thank you for this project , I am trying to use this project and create a NIFI cluster and i see the cluster is failing when i set the `NIFI_CLUSTER_NODE=true` . Any Suggestions here?

**Comment by us3r** [comment]
hello :) are you trying to deploy cluster on the top of mesos ? This image is optimized for that purpose. Pls make sure that you have the latest version of image (force pulling). In case when you want to deploy it outside the mesos then you have to rewrite the zookeeper connection string.

**Comment by raghu999** [comment]
@us3r I am Using DC/OS 1.10 and trying to launch using latest 1.3.0 image when i launch a cluster and scale the instance to more than 2 nifi is failing healthcheck and crashing
```
I1006 02:06:59.584259 16954 executor.cpp:160] Starting task nifi.09404a30-aa3b-11e7-ad5a-e2f5044ef6bf
W1006 02:06:59.584259 16951 logging.cpp:91] RAW: Received signal SIGTERM from process 15468 of user 0; exiting
```

**Comment by us3r** [comment]
ahh.. it looks like that my PR with the newest version of nifi package is still panding. You can find a newest version of universe package in my github

**Comment by raghu999** [comment]
Seems like its been added to the Universe/Catlog. Thanks
